### ISSUE TITLE
Add silent arguments for installation processes

### ISSUE THREAD

**Issue by emilwojcik93** [ajay9634/Ajay-prefix#6]
Hi, some packages has available silent arguments that can be passed while setup binaries are executed
- `./oalinst.exe /s` source: [OpenAL.OpenAL.installer.yaml](https://github.com/eemailme/winget-pkgs/blob/a1e661bd2676f546f062f3a0d823e57893a42c01/manifests/o/OpenAL/OpenAL/1.1/OpenAL.OpenAL.installer.yaml#L15)
- `./nGlide210_setup.exe /S`  [NullSoft - Silent Installers/Uninstallers](https://nsis.sourceforge.io/Docs/Chapter4.html#silent) and [ZeusSoftware.nGlide.installer.yaml](https://github.com/eemailme/winget-pkgs/blob/a1e661bd2676f546f062f3a0d823e57893a42c01/manifests/z/ZeusSoftware/nGlide/2.10/ZeusSoftware.nGlide.installer.yaml#L7)

Rest of packages that can be automatically installed and also silently (some of those packages are currently part of this prefix): [steamtinkerlaunch](https://github.com/sonic2kk/steamtinkerlaunch/blob/master/eval/order.txt)

If you share with me some details about structure of this code and how to prepare development env then I can make a PR of changes that should be made for those changes.

Best,
emilwojcik93

**Comment by ajay9634** [comment]
Thanks I will test OpenAL and nglide with silent cmd.

I added some net framework and other fixes in Ajay prefix beta 2.
Update script from the start menu.

Still improving some cmd.

You can tell me if you face any issues.

**Comment by ajay9634** [comment]
Fixed, released Ajay prefix v10.14

**Comment by ajay9634** [comment]
Updated bat files
