### ISSUE TITLE
Wined3d replaces dxvk unintentionally

### ISSUE THREAD

**Issue by raynoxu1337** [ajay9634/Ajay-prefix#8]
Poco f4gt S8gen1, official eu ROM
Winlator 8 rv1 proot Ajay v3
using Ajay's wine preset.
to reproduce:
* create new container with newest ajays preset
* update start menu scripts
* run 3d3 test, d3d test runs normally and reports adreno/turnip
* install gecko
* install mono
* d3d test reports gtx 480, bad fps
* in log i can see its using winded3d

**Comment by raynoxu1337** [comment]
Also installing dxvk from start menu OR from winlator GUI does not fix make it use dxvk

**Comment by ajay9634** [comment]
Weird,
I don't have this issue.![Screenshot_2024-12-30-22-48-12-060_com.winlato8.jpg](https://github.com/user-attachments/assets/7c2a6b0b-444b-47eb-8fc1-a486e170cf29)

This test after installing mono and gecho.

I think you did missteps,
Test in a new container again.

**Comment by ajay9634** [comment]
Check dlls override in regedit.
I think dlls gone to builtin not native.

**Comment by raynoxu1337** [comment]
sounds hard to beleave, but after quitting winlator and opening same container again for a few times it will finally switch to dxvk. I can't know for sure why it happens some times and other times ir did not happen. Anyways, nice job! Im planning to contribute to either winlator or miceWine, as for your repo- great job man ;) Im wondering if the panVK driver is useable on mali g615-mc6, alot of new panVK stuff is already in newest mesa, should have some legitimate dxvk support on mali g610. 
https://www.youtube.com/watch?v=ZOEOff80w6s
https://gitlab.freedesktop.org/mesa/mesa/-/commits/main?search=panvk

**Comment by ajay9634** [comment]
I accept sometimes winlator is buggy, but this issue is not from me. As far I tested, I didn't face this issue. I only faced container crashing issue.
The only solution is edit container settings and change dxvk version then Restart the container.

Thanks for contribution.
If want to contribute on my Emuplay0 discord. you are welcome.
